# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argoimagescaler
  namespace: default
type: Opaque
data:
  SCALE_DOWN_POD_COUNT: MA==
  SCALE_UP_POD_COUNT: MQ==
  SCALE_UP_TIME: MDk=
  SCALE_DOWN_TIME: MTY=
